version: "3.8"  # Docker Compose file format version
 
services:
  dog-auth-api:  # Name of the service
    container_name: dog-auth-api  # Name of the container
    image: dog-auth-api:latest  # Docker image to be used for the service
    build:
      context: ./  # Path to the Dockerfile for building the image
    volumes:
      - "./:/app"  # Mounting the current directory to /app directory inside the container
      - "/app/node_modules"
    ports:
      - "3000:3000"  # Port mapping from host to container (host:container)
      - "5858:5858"  # Another port mapping (Debugging)
    env_file:
      - .env  # Environment variable file to be used by the service
    restart: always  # Restart policy for the container
    networks:
      - docker-doks  # Attaching the service to the defined network
    logging:
      driver: "json-file"  # Logging driver to use
      options:
        max-file: "5"  # Maximum number of log files to keep
        max-size: "10m"  # Maximum size of each log file
    deploy:
      resources:
        limits:
          cpus: "0.80"  # CPU limit for the service
          memory: 1g  # Memory limit for the service
 
 
networks:
  docker-doks:  # Definition of the custom bridge network
    driver: bridge  # Using the bridge network driver
 